---
name: "Deploy to Screeps.com"

on:
    push:
        branches: [master, dev]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm i

            - name: Load credentials
              run: echo '${{ secrets.SCREEPS_CREDENTIALS }}' > screeps.json

            - name: Build and deploy to dev
              if: github.ref == 'refs/heads/dev'
              run: |
                  pnpm push-dev

            - name: Build and deploy to main
              if: github.ref == 'refs/heads/master'
              run: |
                  pnpm push-main
